# Main configuration for the conversational dataset generator
# Customize the parameters below as needed

# Output format: chatml, sharegpt, alpaca, json, jsonl, csv
output_format: chatml

# Number of conversations to generate
num_examples: 2

# Model temperature (0.1-1.0, lower values = more precise answers)
temperature: 0.7

# Number of turns per conversation (user/assistant alternated)
turns_per_conversation: 2

# Domain/context of the conversations (used in prompts, will be inserted literally in system prompts)
domain: "Medical assistance"

# Output file path (will be created as a valid JSON array)
output_file: "datasets/dataset.jsonl"

# If true, extends an existing dataset instead of overwriting
extend_existing: false

# DeepSeek API key
api_key: "sk-80ed9427de1b4ad3a0857fca7ceec6a8"

# Maximum number of attempts for each API call
max_retries: 5

# Seconds to wait between retries in case of error/rate limit
retry_backoff: 2

# Detailed log file
log_file: "generation.log"

# If true, enables chain-of-thought (step-by-step reasoning) answers
chain_of_thought: false

# If true, includes a unique "id" field for each conversation in the dataset
include_id: false
